#globals file
VALUE_COEFFICIENT = 0.5 #USED TO DESCRIBE THE VALUE OF ITEMS THROUGHOUT THE GAME (LOWER NUMBER = MORE GOLD VALUE PER ITEM)
DIFFICULTY = 1 #1 IS STANDARD, 2 IS HARD, 3 IS INSANE, 4 IS JUST OUTRAGEOUS
GAMERATE = 4 #THIS IS THE RATE AT WHICH THE GAME SLEEPS OCCUR
WIDTH = 80
HEIGHT= 30